version: '3.1'
services:
  nginx:
    build: 
     context: .
    container_name: reactapp   
    ports:
      - 80:80
    volumes:
      - customvolume:/usr/share/nginx/html/

volumes:
  customvolume:

