version: '3.1'
services:
  nginx:
    image: reactimage
    container_name: reactcontainer   
    ports:
      - 80:80
    volumes:
      - customvolume:/usr/share/nginx/html/

volumes:
  customvolume:

