apiVersion: v1
kind: Pod
metadata:
  name: reactapp
  labels: 
    app: react-pod
spec:
  containers:
  - name: containerimagefromdevrepo
    image: suryaln/capstonereactimage:latest
    ports:
    - containerPort: 80
