apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: react-s
spec:
  selector:
    app: react-d
  type: LoadBalancer
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80  
